### PR TITLE
Fix #7169: rewrite assert_readonly to check property descriptors

### LINKED ISSUE #7169: 'assert_readonly' implementation is problematic
Originally posted as https://github.com/w3c/testharness.js/issues/177 by @DLehenbauer on 19 Jan 2016, 22:32 UTC:

> @AlexeyKor recently noticed unexpected results from 'assert_readonly()' and dug into why.  He found that the current implementation tests for readonly by attempting to set the current value and inspecting the property afterward to see if the value changed:
> 
> ``` javascript
> function assert_readonly(object, property_name, description)
> {
>     var initial_value = object[property_name];
>     try {
>         //Note that this can have side effects in the case where
>         //the property has PutForwards
>         object[property_name] = initial_value + "a"; //XXX use some other value here?
>         assert(same_value(object[property_name], initial_value),
>                    "assert_readonly", description,
>                    "changing property ${p} succeeded",
>                    {p:property_name});
>     } finally {
>         object[property_name] = initial_value;
>     }
> }
> ```
> 
> This is problematic, as `initial_value + 'a'` is not guaranteed to be valid value for the property, in which case the set attempt might throw, or be silently ignored even if the property is writable.  (This is particularly true if the property doesn't accept strings.)
> 
> I'm guessing this code predates ES5, and now should be updated to inspect the property's descriptor.  We can potentially go a step further, and ensure that attempting to set the property in a 'use strict' block throws the proper error.
> 
> If this seems uncontroversial, @AlexeyKor or I are happy to implement.

### PR DESCRIPTION
**Pull request by gsnedders**
This changes the implementation to only check that the property descriptor makes the property readonly; it doesn't actually check its behaviour. As detailed in the above issue, there's too many ways for this test to be otherwise bogus, thus we should go for the simple implementation.

This also fixes /css/cssom/cssimportrule.html, which previously asserted that CSSImportRule#media was readonly, which was a meaningless test, as even after the `[PutForwards]` `[[Set]]` call had occurred, the attribute being tested still returned the same object, because it is defined with `[SameObject]`.

Fixes #7169.

### CODE REVIEW

**Review by dbaron — APPROVED** [review]
I guess the cssimportrule.html change looks fine to me, but I'll leave it to someone else to review the rest. :-)

File: resources/testharness.js [hunk 1]
```diff
@@ -2032,30 +2032,46 @@
...
+               {p:property_name});
+
+        if (desc.hasOwnProperty("value")) {
+            // We're a data property descriptor
+            assert(desc.writable === false, "assert_readonly", description,
+                   "descriptor [[Writable]] expected false got ${actual}", {actual:desc.writable});
+        } else if (desc.hasOwnProperty("get") || desc.hasOwnProperty("set")) {
+            // We're an accessor property descriptor
+            assert(desc.set === undefined, "assert_readonly", description,
+                   "property ${p} is an accessor property with a [[Set]] attribute, cannot test readonly-ness",
```
Comment (Ms2ger) [inline resources/testharness.js:2065]: "cannot test" seems like an odd phrasing - I guess there could be read-write properties that always fail to set, but that seems out of scope here

**Review by Ms2ger — APPROVED** [review]
Thanks!

File: resources/testharness.js (hunk 1 above)
Comment (gsnedders) [reply resources/testharness.js:2065]: I mean some of this gets into existential questions of "what does it mean for a property to be readonly", which is kinda unclear. We should maybe/probably just deprecate this entirely.
