### PR TITLE
testharness.js: Support BigInts in assert_greater_than etc

### LINKED ISSUE #51331: testharness.js: Support BigInts in assert_greater_than() etc
Currently, if you `assert_greater_than(2n, 1n)`  you'll get a failure "expected a number but got a bigint". This is due to a `typeof actual === "number"` assertion in the assertion function itself. Comparing a BigInt against another BigInt with the relational operators works, so this could be relaxed to allow "number" or "bigint". Comparing a BigInt against a Number will fail, which is fine.

Relevant functions:
* assert_less_than()
* assert_greater_than()
* assert_less_than_equal()
* assert_greater_than_equal()
* assert_between_exclusive()
* assert_between_inclusive()

Context: [This WebNN test helper](https://github.com/web-platform-tests/wpt/blob/df1069e522fc6eee7b99cf29f95539aae0a48020/webnn/resources/utils.js#L302) does a `>` comparison of values which are often BigInts (depends on the data type being tested), and can't use `assert_less_than_equal()`

### PR DESCRIPTION
**Pull request by inexorabletash**
Resolves #51331

### CODE REVIEW

File: resources/testharness.js [hunk 1]
```diff
@@ -1795,20 +1802,25 @@
...
+         * Test if a primitive number (or bigint) is greater than another
          */
-        assert(typeof actual === "number",
+        assert(typeof actual === "number" || typeof actual === "bigint",
                "assert_greater_than", description,
                "expected a number but got a ${type_actual}",
                {type_actual:typeof actual});
 
+        assert(typeof actual === typeof expected,
+               "assert_less_than", description,
```
Comment (foolip) [inline resources/testharness.js:1820]: This and following instances of "assert_less_than" need to be updated.

File: resources/testharness.js [hunk 2]
```diff
@@ -1771,20 +1773,25 @@
...
-         * Test if a primitive number is less than another
+         * Test if a primitive number (or bigint) is less than another
          */
-        assert(typeof actual === "number",
+        assert(typeof actual === "number" || typeof actual === "bigint",
                "assert_less_than", description,
                "expected a number but got a ${type_actual}",
                {type_actual:typeof actual});
 
+        assert(typeof actual === typeof expected,
```
Comment (foolip) [inline resources/testharness.js:1790]: Doesn't comparison between numbers and bigints work, or why must the types match?

**Review by foolip — APPROVED** [review]
Supporting BigInt here makes a lot of sense. I will be OOO next week so if you need help landing this I will have to defer to @past.

File: resources/testharness.js (hunk 1 above)
Comment (inexorabletash) [reply resources/testharness.js:1820]: Oops, thanks.

Comment (inexorabletash) [reply resources/testharness.js]: Fixed in e7a3c470c2

**Review by Ms2ger — APPROVED** [review]
Makes sense to me

File: resources/testharness.js (hunk 2 above)
Comment (zcorpan) [reply resources/testharness.js:1790]: If I change Gecko to make some API return bigints instead of numbers, I expect tests to fail. testharness.js is usually strict on details like this.

File: resources/testharness.js [hunk 3]
```diff
@@ -1820,21 +1832,31 @@
...
 
+        assert(typeof actual === typeof lower,
+               "assert_between_exclusive", description,
+               "expected a ${type_lower} but got a ${type_actual}",
+               {type_lower:typeof lower, type_actual:typeof actual});
+
+        assert(typeof actual === typeof upper,
+               "assert_between_exclusive", description,
+               "expected a ${type_upper} but got a ${type_actual}",
+               {type_upper:typeof upper, type_actual:typeof actual});
```
[the remark this answers is not in the document]
Comment (inexorabletash) [reply resources/testharness.js]: Done in f584673f57 - please take a look?

File: resources/testharness.js [hunk 4]
```diff
@@ -1897,21 +1929,31 @@
...
 
+        assert(typeof actual === typeof lower,
+               "assert_between_inclusive", description,
+               "expected a ${type_lower} but got a ${type_actual}",
+               {type_lower:typeof lower, type_actual:typeof actual});
+
+        assert(typeof actual === typeof upper,
+               "assert_between_inclusive", description,
+               "expected a ${type_upper} but got a ${type_actual}",
+               {type_upper:typeof upper, type_actual:typeof actual});
```
[the remark this answers is not in the document]
Comment (inexorabletash) [reply resources/testharness.js]: Ditto!

**Comment by inexorabletash** [comment]
@Ms2ger  - could you take a final look and merge if it looks good to you?

File: resources/testharness.js [hunk 5]
```diff
@@ -1820,21 +1832,31 @@
...
+        assert(typeof actual === "number" || typeof actual === "bigint",
                "assert_between_exclusive", description,
                "expected a number but got a ${type_actual}",
                {type_actual:typeof actual});
 
+        assert(typeof lower === typeof upper,
+               "assert_between_exclusive", description,
+               "expected lower (${type_lower}) and upper (${type_upper}) types to match",
+               {type_lower:typeof lower, type_upper:typeof upper});
+
```
Comment (Ms2ger) [inline resources/testharness.js:1854]: Would you mind putting this before the `typeof actual` assert above, and add something like "test error"? It seems to me like this will never be the implementation's fault. (Also in `assert_between_inclusive`.)

**Review by Ms2ger — APPROVED** [review]
Just one more comment (times two). LGTM otherwise, thanks!

(Though I wonder if this technically needs an RFC)

File: resources/testharness.js (hunk 5 above)
Comment (inexorabletash) [reply resources/testharness.js]: Done in c6b3b842fd

**Comment by inexorabletash** [comment]
> (Though I wonder if this technically needs an RFC)

I'll spin one up.

**Comment by inexorabletash** [comment]
https://github.com/web-platform-tests/rfcs/pull/222

**Review by jgraham — APPROVED** [review]

**Comment by inexorabletash** [comment]
https://github.com/web-platform-tests/rfcs/blob/master/rfcs/bigint_support.md is now merged so I think this is good to go? @ms2ger please let me know if anything else is needed on my part.

**Review by Ms2ger — APPROVED** [review]
Thanks!

**Comment by Ms2ger** [comment]
Looks like the failure is legitimate:
```

            {
                'args': [
                    '10',
                    '11',
  +                 '"10 is less than 11"',
  -                 '1',
  ?             ^^^^^^^
  +             ],
  ?             ^
  -                 '"10 is approximately (+/- 1) 11"',
  -             ],
  -             'assert_name': 'assert_approx_equals',
  ?                                     ^^^^^^^^^^^^
  +             'assert_name': 'assert_less_than',
  ?                                    +++++++ ^
                'status': 0,
                'test': 'basic assert_less_than test',
  +         },
  +         {
  +             'args': [
  +                 '10n',
  +                 '11n',
  +                 '"10n is not greater than 11n"',
  +             ],
  +             'assert_name': 'assert_greater_than',
  +             'status': 1,
  +             'test': 'bigint assert_greater_than expected to fail',
  +         },
  +         {
  +             'args': [
  +                 '10n',
  +                 '10n',
  +                 '"10n is greater than or equal to 10n"',
  +             ],
  +             'assert_name': 'assert_greater_than_equal',
  +             'status': 0,
  +             'test': 'bigint assert_greater_than_equal test',
  +         },
  +         {
  +             'args': [
  +                 '10n',
  +                 '11n',
  +                 '"10n is less than 11n"',
  +             ],
  +             'assert_name': 'assert_less_than',
  +             'status': 0,
  +             'test': 'bigint assert_less_than test',
            },
```

**Comment by inexorabletash** [comment]
> Looks like the failure is legitimate:
> 
> ```
>   -             'assert_name': 'assert_approx_equals',
>   ?                                     ^^^^^^^^^^^^
>   +             'assert_name': 'assert_less_than',
>   ?                                    +++++++ ^
>                 'status': 0,
>                 'test': 'basic assert_less_than test',
> ```

This test was incorrect - the test name is "basic assert_less_than test" but it was testing a different assertion function, looked like a bad copy/paste to me. I fixed the test.

> ```
>   +             'test': 'bigint assert_greater_than expected to fail',
>   +             'test': 'bigint assert_greater_than_equal test',
>   +             'test': 'bigint assert_less_than test',
> ```

These are from the addition of new test cases. 

As I noted above:

> I can't tell if those Mozilla failures indicate a problem with the PR. e.g. in https://community-tc.services.mozilla.com/tasks/ZX6tPHbzREC-Z8ymLHlUaA/runs/0/logs/public/logs/live.log it is showing a diff because new test cases were added. Is that just an expectation file on the Moz side that needs updating? Guidance is welcome!

**Comment by Ms2ger** [comment]
The expectations are lower down in the test file itself

**Comment by inexorabletash** [comment]
> The expectations are lower down in the test file itself

Ah, thanks - I'd missed that there were effectively _two_ sets of expectations for each test case.

**Comment by inexorabletash** [comment]
There we go, looks all ✅ to me. @Ms2ger can you please confirm and hit the button?

**Comment by Ms2ger** [comment]
Thanks!

**Comment by anonrig** [comment]
FYI: this change broke undici WPT tests. https://github.com/nodejs/undici/issues/4225

**Comment by inexorabletash** [comment]
> FYI: this change broke undici WPT tests. [nodejs/undici#4225](https://github.com/nodejs/undici/issues/4225)

That's unfortunate. And yeah the failure shows in https://wpt.fyi/results/xhr/formdata/append.any.html?label=experimental&label=master&aligned - the stricter "types must match" requirement was introduced _after_ I'd used Chromium's CI to validate the change.

The good news is that https://chromium-review.googlesource.com/c/chromium/src/+/6512012 (the auto-roll of the change into Chromium) only flagged that one test as getting a new failure expectation so I suspect it really is just that one test that needs to be fixed.

**Comment by inexorabletash** [comment]
Addendum: I'll put up a change on the Chromium side to update that formdata test. Hopefully that can get done next week and before I turn into a pumpkin.
