### PR TITLE
testdriver.js: clarify what's not implemented + use async

### LINKED ISSUE #37494: Cryptic errors messages
When running async/promise tests, test harness usually fails with cryptic errors like:

```
promise_test: Unhandled rejection with value: object "Error: unimplemented"
get_stack@https://wpt.live/resources/testharness.js:4521:30
AssertionError@https://wpt.live/resources/testharness.js:4514:31
assert@https://wpt.live/resources/testharness.js:4498:37
@https://wpt.live/resources/testharness.js:764:35
@https://wpt.live/resources/testharness.js:2596:30
@https://wpt.live/resources/testharness.js:2643:40
```

Which are actually caused by testdriver.js (note the lack of mention of testdriver.js above). 

It would be great if testdriver.js at least reported *what* was unimplemented.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #37494 

Also, "unimplemented" is confusing (it reads like, "it was implemented, but now isn't"). Shouldn't it be "not implemented" instead? 

There are also confusing messages for when in automation, but it reports as "unimplemented". I changed those to messages so it's a bit more clear why the error happens.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@jgraham, ping 🙏

File: resources/testdriver.js [hunk 1]
```diff
@@ -657,31 +657,31 @@
          */
         in_automation: false,
 
-        click: function(element, coords) {
+        async click(element, coords) {
             if (this.in_automation) {
-                return Promise.reject(new Error('Not implemented'));
+                throw new Error("click() can't be called in automation");
```
Comment (gsnedders) [inline resources/testdriver.js:662]: so what do I use instead, if I'm trying to click on something in automation?

this new error message would make me believe that I simply can't click on things in automation, would seems like a very common use-case

File: resources/testdriver.js [hunk 2]
```diff
@@ -657,31 +657,31 @@
...
 
             return new Promise(function(resolve, reject) {
                 element.addEventListener("click", resolve);
             });
         },
 
-        delete_all_cookies: function(context=null) {
-            return Promise.reject(new Error("unimplemented"));
+        async delete_all_cookies(context=null) {
+            throw new Error("delete_all_cookies() is not implemented by test_driver_internal");
```
Comment (gsnedders) [inline resources/testdriver.js:671]: We should perhaps make it more explicit that the real problem is it isn't implemented by `testdriver-vendor.js` (or whatever the file is called), rather than mentioning the (most irrelevant) existence of the `test_driver_internal` object?

File: resources/testdriver.js (hunk 1 above)
Comment (marcoscaceres) [reply resources/testdriver.js:662]: ok, yeah, good point... Let me see if I can find some better wording or figure out why this is "not implemented".

File: resources/testdriver.js (hunk 2 above)
Comment (marcoscaceres) [reply resources/testdriver.js:671]: That's a good point.

**Comment by marcoscaceres** [comment]
argh... something went bad with the rebase.

**Comment by marcoscaceres** [comment]
@gsnedders, any better?

File: resources/testdriver.js [hunk 3]
```diff
@@ -691,31 +691,31 @@
          */
         in_automation: false,
 
-        click: function(element, coords) {
+        async click(element, coords) {
             if (this.in_automation) {
-                return Promise.reject(new Error('Not implemented'));
+                throw new Error("click() can't be called when test_driver_internal.in_automation is true");
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply resources/testdriver.js:696]: yeah, I can live with that.

Comment (marcoscaceres) [inline resources/testdriver.js:696]:
```suggestion
                throw new Error("click() is not implemented by test driver-vendor.js");
```

Comment (gsnedders) [reply resources/testdriver.js:696]: this never got applied, seemingly

File: resources/testdriver.js [hunk 4]
```diff
@@ -691,31 +691,31 @@
...
-            return Promise.reject(new Error("unimplemented"));
+        async get_named_cookie(name, context=null) {
+            throw new Error("get_named_cookie() is not implemented by testdriver-vendor.js");
         },
 
-        send_keys: function(element, keys) {
+        async send_keys(element, keys) {
             if (this.in_automation) {
-                return Promise.reject(new Error('Not implemented'));
+                throw new Error("send_keys() can't be called when test_driver_internal.in_automation is true");
```
Comment (gsnedders) [inline resources/testdriver.js:718]: same as click above

Comment (marcoscaceres) [inline resources/testdriver.js:718]:
```suggestion
                throw new Error("send_keys() is not implemented by test driver-vendor.js");
```

Comment (marcoscaceres) [reply resources/testdriver.js]: oops. Hopefully all good now.

File: resources/testdriver.js [hunk 5]
```diff
@@ -691,31 +691,31 @@
          */
         in_automation: false,
 
-        click: function(element, coords) {
+        async click(element, coords) {
             if (this.in_automation) {
-                return Promise.reject(new Error('Not implemented'));
+                throw new Error("click() is not implemented by test driver-vendor.js");
```
Comment (gsnedders) [inline resources/testdriver.js:696]:
```suggestion
                throw new Error("click() is not implemented by testdriver-vendor.js");
```

File: resources/testdriver.js [hunk 6]
```diff
@@ -691,31 +691,31 @@
...
-            return Promise.reject(new Error("unimplemented"));
+        async get_named_cookie(name, context=null) {
+            throw new Error("get_named_cookie() is not implemented by testdriver-vendor.js");
         },
 
-        send_keys: function(element, keys) {
+        async send_keys(element, keys) {
             if (this.in_automation) {
-                return Promise.reject(new Error('Not implemented'));
+                throw new Error("send_keys() is not implemented by test driver-vendor.js");
```
Comment (gsnedders) [inline resources/testdriver.js:718]:
```suggestion
                throw new Error("send_keys() is not implemented by testdriver-vendor.js");
```

File: resources/testdriver.js [hunk 7]
```diff
@@ -745,65 +745,64 @@
...
-        add_virtual_authenticator: function(config, context=null) {
-            return Promise.reject(new Error("unimplemented"));
+        async add_virtual_authenticator(config, context=null) {
+            throw new Error("add_virtual_authenticator() is not implemented by testdriver-vendor.js");
         },
 
-        remove_virtual_authenticator: function(authenticator_id, context=null) {
-            return Promise.reject(new Error("unimplemented"));
+        async remove_virtual_authenticator(authenticator_id, context=null) {
+            throw new Error("remove_virtual_authenticator() not implemented");
```
Comment (gsnedders) [inline resources/testdriver.js:777]:
```suggestion
            throw new Error("remove_virtual_authenticator() is not implemented by testdriver-vendor.js");
```

**Review by gsnedders — COMMENTED** [review]
I vaguely wonder if we should just define a `function TestDriverNotImplementedError(method) { return new Error(method +  "() is not implemented by testdriver-vendor.js") }`?

File: resources/testdriver.js (hunk 5 above)
Comment (marcoscaceres) [reply resources/testdriver.js:696]: Course you autocorrect!

**Review by gsnedders — APPROVED** [review]

File: resources/testdriver.js [hunk 8]
```diff
@@ -691,31 +691,31 @@
          */
         in_automation: false,
 
-        click: function(element, coords) {
+        async click(element, coords) {
```
Comment (Goosensmarjin) [inline resources/testdriver.js:694]: Element coords
