### PR TITLE
Fix #3953: Minor problems with setMediaKeys test

### LINKED ISSUE #3953: [eme] *-mp4-setmediakeys-multiple-times-with-different-mediakeys.html have syntax error
```
setmediakeys-multiple-times-with-different-mediakeys.js:56 Uncaught SyntaxError: Unexpected token )
```

There appears to be an extra `)` after a `then(` without a `test.step_func(`. I tried fixing it but ran into a couple other problems, so someone familiar with this test should look at it.

Also, is there a reason that not all of the resolve functions use `test.step_func()`?

### PR DESCRIPTION
**Pull request by mwatson2**

### CODE REVIEW

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 1]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
             // Set mediaKeys2 on video element (switching MediaKeys) need not
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: This could probably be clearer. For example, "It is up the the implementation whether to allow the MediaKeys to be changed after setting the source. The following step handles both cases."

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 2]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
             // fail after src attribute is set.
             return _video.setMediaKeys(_mediaKeys2);
-        })).then(test.step_func(function() {
+        }).then(test.step_func(function() {
             // Switching setMediaKeys after setting src attribute on video element
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: This seems to say the same thing as above. Instead, it could say "Switching MediaKeys succeeded..."

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 3]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
             // is not required to fail.
-            assert_equals(_video2.mediaKeys, _mediaKeys2);
             fail = false;
+            assert_equals(_video.mediaKeys, _mediaKeys2);
             return Promise.resolve();
-        }, test.step_func(function(error) {
+        }), test.step_func(function(error) {
             fail = true;
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: And a similar comment here.

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 4]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
             assert_equals(_video.mediaKeys, _mediaKeys1);
             assert_in_array(error.name, ['InvalidStateError','NotSupportedError']);
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: Isn't there only one correct exception? I'm fine with having this for the purposes of making progress, but we should have an open issue and reference it here.

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 5]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
             // fail after src attribute is set.
             return _video.setMediaKeys(_mediaKeys2);
-        })).then(test.step_func(function() {
+        }).then(test.step_func(function() {
             // Switching setMediaKeys after setting src attribute on video element
             // is not required to fail.
-            assert_equals(_video2.mediaKeys, _mediaKeys2);
             fail = false;
+            assert_equals(_video.mediaKeys, _mediaKeys2);
             return Promise.resolve();
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: // Return something so the promise resolves properly.

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 6]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
+            assert_equals(_video.mediaKeys, null);
+            test.done();
         }), test.step_func(function(error) {
             if(fail) {
                 assert_equals(_video.mediaKeys, _mediaKeys1);
             } else {
                 assert_equals(_video.mediaKeys, _mediaKeys2);
             }
-            assert_is_array(error.name, ['InvalidStateError','ReferenceError']);
+            assert_in_array(error.name, ['InvalidStateError','ReferenceError']);
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: Ditto, though I'm not sure why `ReferenceError` would occur.

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 7]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
             fail = true;
             assert_equals(_video.mediaKeys, _mediaKeys1);
             assert_in_array(error.name, ['InvalidStateError','NotSupportedError']);
             assert_not_equals(error.message, '');
             // Return something so the promise resolves properly.
             return Promise.resolve();
         })).then(function() {
-            // Set null mediaKeys on video (clearing MediaKeys) not
-            // supported after src attribute is set.
+            // Set null mediaKeys on video (clearing MediaKeys) is not required to fail
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: ditto

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 8]
```diff
@@ -53,34 +53,35 @@ function runTest(config, qualifier) {
...
+            // after src attribute is set.
             return _video.setMediaKeys(null);
         }).then(test.step_func(function() {
-            assert_unreached('Clearing mediaKeys after setting src should have failed.');
+            assert_equals(_video.mediaKeys, null);
+            test.done();
         }), test.step_func(function(error) {
             if(fail) {
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: `fail` is very specific. I think it should have a more specific name reflecting what exactly failed (or passed). Otherwise, it's not obvious why this `.then()` is the way it is.

**Review by ddorwin — CHANGES_REQUESTED** [review]
Thanks for fixing this. Most of my comments are about the existing test.

File: resources [hunk 9]
```diff
@@ -1 +1 @@
-Subproject commit e810600306d0612c609c8daab606229a11061627
+Subproject commit dee0f92b957973785097af3e1b1a5ded9b1e7a94
```
Comment (ddorwin) [inline resources]: I'm assuming this and the next are unintentional.

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 10]
```diff
@@ -50,36 +50,47 @@ function runTest(config, qualifier) {
...
+            // Return something so the promise resolves properly.
             return Promise.resolve();
         }), test.step_func(function(error) {
-            fail = true;
+            // Changing the Media Keys object failed
+            _usingMediaKeys2 = false;
             assert_equals(_video.mediaKeys, _mediaKeys1);
+            // The specification allows wither NotSupportedError or InvalidStateError depending on
+            // whether the failure was because changing Media Keys object is not supported
+            // or just not allowed at this time, respectively.
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: Thank you!

File: encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js [hunk 11]
```diff
@@ -50,36 +50,47 @@ function runTest(config, qualifier) {
...
+            _usingMediaKeys2 = true;
+            assert_equals(_video2.mediaKeys, _mediaKeys2);
+            // Return something so the promise resolves properly.
             return Promise.resolve();
         }), test.step_func(function(error) {
-            fail = true;
+            // Changing the Media Keys object failed
+            _usingMediaKeys2 = false;
             assert_equals(_video.mediaKeys, _mediaKeys1);
+            // The specification allows wither NotSupportedError or InvalidStateError depending on
```
Comment (ddorwin) [inline encrypted-media/scripts/setmediakeys-multiple-times-with-different-mediakeys.js]: **e**ither
Same below

**Review by ddorwin — APPROVED** [review]
LGTM with typo and reverting subresource change (I assume).
