### PR TITLE
[eme] Fix #4279: Don't expect empty configuration to pass

### LINKED ISSUE #4279: [eme] requestmediakeysystemaccess tests expect empty configuration to be valid
[clearkey-mp4-requestmediakeysystemaccess.html ](https://w3c-test.org/encrypted-media/clearkey-mp4-requestmediakeysystemaccess.html) (and the drm variant) currently expect that the empty configuration [{}] is valid (in tests "Empty configuration", "Two configurations, one supported", and "Two configurations, both supported"). Since the spec states that one of 'audioCapabilities' or 'videoCapabilities' must be provided, it appears that these tests are incorrect.

"Empty configuration" should expect to fail, while the other 2 tests should add an 'audioCapabilities' or 'videoCapabilities' to the configurations.

Currently Chrome and Firefox pass the existing tests, while Edge does not.

### PR DESCRIPTION
**Pull request by jrummell-chromium**
The spec states that one of 'audioCapabilities' or 'videoCapabilities' must be provided, so expect failure if one is not provided. Update 2 other tests to include 'videoCapabilities' so that they continue to succeed on implementations that match the spec.

### CODE REVIEW

**Review by joeyparrish — APPROVED** [review]

File: encrypted-media/scripts/requestmediakeysystemaccess.js [hunk 1]
```diff
@@ -156,13 +156,16 @@ function runTest(config, qualifier) {
     }], 'NotSupportedError', 'Mismatched audio container/codec (%audiocontenttype)');
 
     expect_config(config.keysystem, [
-        {initDataTypes: ['fakeidt']},
-        {initDataTypes: [config.initDataType]}
+        {initDataTypes: ['fakeidt'],
+         videoCapabilities: [{contentType: config.videoType}]},
+        {initDataTypes: [config.initDataType],
+         videoCapabilities: [{contentType: config.videoType}]}
     ], {initDataTypes: [config.initDataType]}, 'Two configurations, one supported');
```
Comment (ddorwin) [inline encrypted-media/scripts/requestmediakeysystemaccess.js]: Please add videoCapabilities to the expected result here and below.

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234993513)

# Firefox (nightly) #
Testing web-platform-tests at revision c2b005608544ecf0615e25515cfb6e41a81fe367
Using browser at version BuildID 20170522100359; SourceStamp 9851fcb0bf4d855c36729d7de19f0fa5c9f69776
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4287/encrypted-media/clearkey-mp4-requestmediakeysystemaccess.html">/encrypted-media/clearkey-mp4-requestmediakeysystemaccess.html</a></summary>


|                                                                                                                   Subtest                                                                                                                    | Results |                                                        Messages                                                       |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                                                                              | OK      |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Empty Key System should result in TypeError`                                                                                                                                                  | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unsupported Key System should result in NotSupportedError`                                                                                                                                    | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Key System ending in "." should result in NotSupportedError`                                                                                                                                  | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Capitalized Key System should result in NotSupportedError`                                                                                                                                    | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Non-ASCII Key System should result in NotSupportedError`                                                                                                                                      | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Root domain of Key System alone should result in NotSupportedError`                                                                                                                           | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Root domain of Key System, with dot should result in NotSupportedError`                                                                                                                       | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Domain of Key System along should result in NotSupportedError`                                                                                                                                | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Domain of Key System, with dot should result in NotSupportedError`                                                                                                                            | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Child of Key System should result in NotSupportedError`                                                                                                                                       | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Prefixed Key System should result in NotSupportedError`                                                                                                                                       | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Missing characters in middle of Key System name should result in NotSupportedError`                                                                                                           | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Missing characters at end of Key System name should result in NotSupportedError`                                                                                                              | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Leading space in Key System name should result in NotSupportedError`                                                                                                                          | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Extra space in Key System name should result in NotSupportedError`                                                                                                                            | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Trailing space in Key System name should result in NotSupportedError`                                                                                                                         | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Leading dot in Key System name should result in NotSupportedError`                                                                                                                            | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Extra dot in middle of Key System name should result in NotSupportedError`                                                                                                                    | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Trailing dot in Key System name should result in NotSupportedError`                                                                                                                           | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Key System name is case sensitive should result in NotSupportedError`                                                                                                                         | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Empty supportedConfigurations should result in TypeError`                                                                                                                                     | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Empty configuration should result in NotSupportedError`                                                                                                                                       | PASS    |                                                                                                                       |
| `Basic supported configuration`                                                                                                                                                                                                              | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Partially supported configuration`                                                                                                                                                                                                          | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Supported audio codec`                                                                                                                                                                                                                      | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `ContentType formatting must be preserved`                                                                                                                                                                                                   | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unsupported audio codec ('audio/webm; codecs=fake') should result in NotSupportedError`                                                                                                       | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unsupported video codec () should result in NotSupportedError`                                                                                                                                | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/webm; codecs=mp4a','audio/webm; codecs=mp4a.40.2') should result in NotSupportedError`                                                               | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Video codec specified in audio field ('video/mp4;codecs="avc1.4d401e"') should result in NotSupportedError`                                                                                   | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Audio codec specified in video field ('audio/mp4;codecs="mp4a.40.2"') should result in NotSupportedError`                                                                                     | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/webm; codecs=avc1','audio/webm; codecs=avc1.42e01e') should result in NotSupportedError`                                                             | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/mp4; codecs=vorbis') should result in NotSupportedError`                                                                                             | PASS    |                                                                                                                       |
| `Two configurations, one supported`                                                                                                                                                                                                          | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Two configurations, both supported`                                                                                                                                                                                                         | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Audio MIME type does not support video codecs (webm) ('audio/webm; codecs="vp8,vorbis"','audio/webm; codecs="vorbis, vp8"','audio/webm; codecs="vp8"') should result in NotSupportedError`    | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Audio MIME type does not support video codecs (mp4) ('audio/mp4; codecs="avc1"','audio/mp4; codecs="avc1.4d401e"') should result in NotSupportedError`                                        | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Video MIME type does not support audio codecs (webm) ('video/webm; codecs="vp8,vorbis"','video/webm; codecs="vorbis, vp8"','video/webm; codecs="vorbis"') should result in NotSupportedError` | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Video MIME type does not support audio codecs (mp4) ('video/mp4; codecs="mp4a"','video/mp4; codecs="mp4a.40.2"') should result in NotSupportedError`                                          | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: WebM audio does not support AVC1/AAC ('audio/webm; codecs="aac"','audio/webm; codecs="avc1"','audio/webm; codecs="vp8,aac"') should result in NotSupportedError`                              | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: WebM video does not support AVC1/AAC ('video/webm; codecs="aac"','video/webm; codecs="avc1"','video/webm; codecs="vp8,aac"') should result in NotSupportedError`                              | PASS    |                                                                                                                       |
| `Leading space in contentType`                                                                                                                                                                                                               | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Space before ; in contentType`                                                                                                                                                                                                              | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Trailing space in contentType`                                                                                                                                                                                                              | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Space at start of codecs parameter`                                                                                                                                                                                                         | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Space at end of codecs parameter`                                                                                                                                                                                                           | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Video/`                                                                                                                                                                                                                                     | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Codecs=`                                                                                                                                                                                                                                    | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `Upper case MIME type`                                                                                                                                                                                                                       | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `CODECS=`                                                                                                                                                                                                                                    | FAIL    | `promise_test: Unhandled rejection with value: object "NotSupportedError: Key system configuration is not supported"` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unrecognized foo with webm ('video/webm; foo="bar"') should result in NotSupportedError`                                                                                                      | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unrecognized foo with mp4 ('video/mp4; foo="bar"') should result in NotSupportedError`                                                                                                        | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unrecognized foo with codecs ('video/mp4;codecs="avc1.4d401e"; foo="bar"') should result in NotSupportedError`                                                                                | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'fake' should result in NotSupportedError`                                                                                                                                       | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'audio/fake' should result in NotSupportedError`                                                                                                                                 | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'video/fake' should result in NotSupportedError`                                                                                                                                 | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'video/mp4;codecs="AVC1.4D401E"' should result in NotSupportedError`                                                                                                             | PASS    |                                                                                                                       |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'video/mp4;codecs=",avc1.4d401e"' should result in NotSupportedError`                                                                                                            | PASS    |                                                                                                                       |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4287/encrypted-media/drm-mp4-requestmediakeysystemaccess.html">/encrypted-media/drm-mp4-requestmediakeysystemaccess.html</a></summary>


|                                                                                                             Subtest                                                                                                              | Results |     Messages     |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------|
|                                                                                                                                                                                                                                  | TIMEOUT |                  |
| `drm, requestMediaKeySystemAccess: Empty Key System should result in TypeError`                                                                                                                                                  | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Unsupported Key System should result in NotSupportedError`                                                                                                                                    | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Key System ending in "." should result in NotSupportedError`                                                                                                                                  | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Capitalized Key System should result in NotSupportedError`                                                                                                                                    | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Non-ASCII Key System should result in NotSupportedError`                                                                                                                                      | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Root domain of Key System alone should result in NotSupportedError`                                                                                                                           | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Root domain of Key System, with dot should result in NotSupportedError`                                                                                                                       | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Domain of Key System along should result in NotSupportedError`                                                                                                                                | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Domain of Key System, with dot should result in NotSupportedError`                                                                                                                            | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Child of Key System should result in NotSupportedError`                                                                                                                                       | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Prefixed Key System should result in NotSupportedError`                                                                                                                                       | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Missing characters in middle of Key System name should result in NotSupportedError`                                                                                                           | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Missing characters at end of Key System name should result in NotSupportedError`                                                                                                              | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Leading space in Key System name should result in NotSupportedError`                                                                                                                          | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Extra space in Key System name should result in NotSupportedError`                                                                                                                            | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Trailing space in Key System name should result in NotSupportedError`                                                                                                                         | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Leading dot in Key System name should result in NotSupportedError`                                                                                                                            | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Extra dot in middle of Key System name should result in NotSupportedError`                                                                                                                    | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Trailing dot in Key System name should result in NotSupportedError`                                                                                                                           | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Key System name is case sensitive should result in NotSupportedError`                                                                                                                         | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Empty supportedConfigurations should result in TypeError`                                                                                                                                     | PASS    |                  |
| `drm, requestMediaKeySystemAccess: Empty configuration should result in NotSupportedError`                                                                                                                                       | TIMEOUT | `Test timed out` |
| `Basic supported configuration`                                                                                                                                                                                                  | NOTRUN  |                  |
| `Partially supported configuration`                                                                                                                                                                                              | NOTRUN  |                  |
| `Supported audio codec`                                                                                                                                                                                                          | NOTRUN  |                  |
| `ContentType formatting must be preserved`                                                                                                                                                                                       | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Unsupported audio codec ('audio/webm; codecs=fake') should result in NotSupportedError`                                                                                                       | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Unsupported video codec () should result in NotSupportedError`                                                                                                                                | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/webm; codecs=mp4a','audio/webm; codecs=mp4a.40.2') should result in NotSupportedError`                                                               | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Video codec specified in audio field ('video/mp4;codecs="avc1.4d401e"') should result in NotSupportedError`                                                                                   | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Audio codec specified in video field ('audio/mp4;codecs="mp4a.40.2"') should result in NotSupportedError`                                                                                     | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/webm; codecs=avc1','audio/webm; codecs=avc1.42e01e') should result in NotSupportedError`                                                             | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/mp4; codecs=vorbis') should result in NotSupportedError`                                                                                             | NOTRUN  |                  |
| `Two configurations, one supported`                                                                                                                                                                                              | NOTRUN  |                  |
| `Two configurations, both supported`                                                                                                                                                                                             | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Audio MIME type does not support video codecs (webm) ('audio/webm; codecs="vp8,vorbis"','audio/webm; codecs="vorbis, vp8"','audio/webm; codecs="vp8"') should result in NotSupportedError`    | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Audio MIME type does not support video codecs (mp4) ('audio/mp4; codecs="avc1"','audio/mp4; codecs="avc1.4d401e"') should result in NotSupportedError`                                        | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Video MIME type does not support audio codecs (webm) ('video/webm; codecs="vp8,vorbis"','video/webm; codecs="vorbis, vp8"','video/webm; codecs="vorbis"') should result in NotSupportedError` | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Video MIME type does not support audio codecs (mp4) ('video/mp4; codecs="mp4a"','video/mp4; codecs="mp4a.40.2"') should result in NotSupportedError`                                          | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: WebM audio does not support AVC1/AAC ('audio/webm; codecs="aac"','audio/webm; codecs="avc1"','audio/webm; codecs="vp8,aac"') should result in NotSupportedError`                              | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: WebM video does not support AVC1/AAC ('video/webm; codecs="aac"','video/webm; codecs="avc1"','video/webm; codecs="vp8,aac"') should result in NotSupportedError`                              | NOTRUN  |                  |
| `Leading space in contentType`                                                                                                                                                                                                   | NOTRUN  |                  |
| `Space before ; in contentType`                                                                                                                                                                                                  | NOTRUN  |                  |
| `Trailing space in contentType`                                                                                                                                                                                                  | NOTRUN  |                  |
| `Space at start of codecs parameter`                                                                                                                                                                                             | NOTRUN  |                  |
| `Space at end of codecs parameter`                                                                                                                                                                                               | NOTRUN  |                  |
| `Video/`                                                                                                                                                                                                                         | NOTRUN  |                  |
| `Codecs=`                                                                                                                                                                                                                        | NOTRUN  |                  |
| `Upper case MIME type`                                                                                                                                                                                                           | NOTRUN  |                  |
| `CODECS=`                                                                                                                                                                                                                        | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Unrecognized foo with webm ('video/webm; foo="bar"') should result in NotSupportedError`                                                                                                      | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Unrecognized foo with mp4 ('video/mp4; foo="bar"') should result in NotSupportedError`                                                                                                        | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: Unrecognized foo with codecs ('video/mp4;codecs="avc1.4d401e"; foo="bar"') should result in NotSupportedError`                                                                                | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: contentType: 'fake' should result in NotSupportedError`                                                                                                                                       | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: contentType: 'audio/fake' should result in NotSupportedError`                                                                                                                                 | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: contentType: 'video/fake' should result in NotSupportedError`                                                                                                                                 | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: contentType: 'video/mp4;codecs="AVC1.4D401E"' should result in NotSupportedError`                                                                                                             | NOTRUN  |                  |
| `drm, requestMediaKeySystemAccess: contentType: 'video/mp4;codecs=",avc1.4d401e"' should result in NotSupportedError`                                                                                                            | NOTRUN  |                  |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234993514)

# Sauce (safari) #
Testing web-platform-tests at revision c2b005608544ecf0615e25515cfb6e41a81fe367
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4287/encrypted-media/clearkey-mp4-requestmediakeysystemaccess.html">/encrypted-media/clearkey-mp4-requestmediakeysystemaccess.html</a></summary>


|                                                                                                                   Subtest                                                                                                                    | Results |                                                                                         Messages                                                                                         |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                                                                                              | OK      |                                                                                                                                                                                          |
| `org.w3.clearkey, requestMediaKeySystemAccess: Empty Key System should result in TypeError`                                                                                                                                                  | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unsupported Key System should result in NotSupportedError`                                                                                                                                    | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Key System ending in "." should result in NotSupportedError`                                                                                                                                  | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Capitalized Key System should result in NotSupportedError`                                                                                                                                    | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Non-ASCII Key System should result in NotSupportedError`                                                                                                                                      | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Root domain of Key System alone should result in NotSupportedError`                                                                                                                           | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Root domain of Key System, with dot should result in NotSupportedError`                                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Domain of Key System along should result in NotSupportedError`                                                                                                                                | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Domain of Key System, with dot should result in NotSupportedError`                                                                                                                            | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Child of Key System should result in NotSupportedError`                                                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Prefixed Key System should result in NotSupportedError`                                                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Missing characters in middle of Key System name should result in NotSupportedError`                                                                                                           | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Missing characters at end of Key System name should result in NotSupportedError`                                                                                                              | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Leading space in Key System name should result in NotSupportedError`                                                                                                                          | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Extra space in Key System name should result in NotSupportedError`                                                                                                                            | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Trailing space in Key System name should result in NotSupportedError`                                                                                                                         | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Leading dot in Key System name should result in NotSupportedError`                                                                                                                            | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Extra dot in middle of Key System name should result in NotSupportedError`                                                                                                                    | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Trailing dot in Key System name should result in NotSupportedError`                                                                                                                           | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Key System name is case sensitive should result in NotSupportedError`                                                                                                                         | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Empty supportedConfigurations should result in TypeError`                                                                                                                                     | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Empty configuration should result in NotSupportedError`                                                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Basic supported configuration`                                                                                                                                                                                                              | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Partially supported configuration`                                                                                                                                                                                                          | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Supported audio codec`                                                                                                                                                                                                                      | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `ContentType formatting must be preserved`                                                                                                                                                                                                   | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unsupported audio codec ('audio/webm; codecs=fake') should result in NotSupportedError`                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unsupported video codec () should result in NotSupportedError`                                                                                                                                | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/webm; codecs=mp4a','audio/webm; codecs=mp4a.40.2') should result in NotSupportedError`                                                               | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Video codec specified in audio field ('video/mp4;codecs="avc1.4d401e"') should result in NotSupportedError`                                                                                   | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Audio codec specified in video field ('audio/mp4;codecs="mp4a.40.2"') should result in NotSupportedError`                                                                                     | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/webm; codecs=avc1','audio/webm; codecs=avc1.42e01e') should result in NotSupportedError`                                                             | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Mismatched audio container/codec ('audio/mp4; codecs=vorbis') should result in NotSupportedError`                                                                                             | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Two configurations, one supported`                                                                                                                                                                                                          | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Two configurations, both supported`                                                                                                                                                                                                         | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Audio MIME type does not support video codecs (webm) ('audio/webm; codecs="vp8,vorbis"','audio/webm; codecs="vorbis, vp8"','audio/webm; codecs="vp8"') should result in NotSupportedError`    | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Audio MIME type does not support video codecs (mp4) ('audio/mp4; codecs="avc1"','audio/mp4; codecs="avc1.4d401e"') should result in NotSupportedError`                                        | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Video MIME type does not support audio codecs (webm) ('video/webm; codecs="vp8,vorbis"','video/webm; codecs="vorbis, vp8"','video/webm; codecs="vorbis"') should result in NotSupportedError` | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Video MIME type does not support audio codecs (mp4) ('video/mp4; codecs="mp4a"','video/mp4; codecs="mp4a.40.2"') should result in NotSupportedError`                                          | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: WebM audio does not support AVC1/AAC ('audio/webm; codecs="aac"','audio/webm; codecs="avc1"','audio/webm; codecs="vp8,aac"') should result in NotSupportedError`                              | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: WebM video does not support AVC1/AAC ('video/webm; codecs="aac"','video/webm; codecs="avc1"','video/webm; codecs="vp8,aac"') should result in NotSupportedError`                              | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Leading space in contentType`                                                                                                                                                                                                               | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Space before ; in contentType`                                                                                                                                                                                                              | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Trailing space in contentType`                                                                                                                                                                                                              | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Space at start of codecs parameter`                                                                                                                                                                                                         | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Space at end of codecs parameter`                                                                                                                                                                                                           | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Video/`                                                                                                                                                                                                                                     | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Codecs=`                                                                                                                                                                                                                                    | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `Upper case MIME type`                                                                                                                                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `CODECS=`                                                                                                                                                                                                                                    | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unrecognized foo with webm ('video/webm; foo="bar"') should result in NotSupportedError`                                                                                                      | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unrecognized foo with mp4 ('video/mp4; foo="bar"') should result in NotSupportedError`                                                                                                        | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: Unrecognized foo with codecs ('video/mp4;codecs="avc1.4d401e"; foo="bar"') should result in NotSupportedError`                                                                                | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'fake' should result in NotSupportedError`                                                                                                                                       | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'audio/fake' should result in NotSupportedError`                                                                                                                                 | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'video/fake' should result in NotSupportedError`                                                                                                                                 | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'video/mp4;codecs="AVC1.4D401E"' should result in NotSupportedError`                                                                                                             | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |
| `org.w3.clearkey, requestMediaKeySystemAccess: contentType: 'video/mp4;codecs=",avc1.4d401e"' should result in NotSupportedError`                                                                                                            | FAIL    | `navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(keySystem, configurations)', 'navigator.requestMediaKeySystemAccess' is undefined)` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4287/encrypted-media/drm-mp4-requestmediakeysystemaccess.html">/encrypted-media/drm-mp4-requestmediakeysystemaccess.html</a></summary>


|                               Subtest                                | Results |                                                                                                                              Messages                                                                                                                              |
|----------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                      | OK      |                                                                                                                                                                                                                                                                    |
| `Encrypted Media Extensions: requestMediaKeySystemAccess tests, DRM` | FAIL    | `TypeError: navigator.requestMediaKeySystemAccess is not a function. (In 'navigator.requestMediaKeySystemAccess(\n                        keysystem, getSimpleConfigurationForInitDataType(initDataType))', 'navigator.requestMediaKeySystemAccess' is undefined)` |

</details>
</details>

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234993531)

# Chrome (unstable) #
Testing web-platform-tests at revision c2b005608544ecf0615e25515cfb6e41a81fe367

**Comment by w3c-bots** [comment]
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/234993532)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision c2b005608544ecf0615e25515cfb6e41a81fe367

**Review by ddorwin — APPROVED** [review]
