### PR TITLE
html: fix form constraint validator

### LINKED ISSUE #20825: updated tests for validationMessage inconsistent with the spec
Changes from https://github.com/web-platform-tests/wpt/pull/20663 introduce an issue for `validationMessage`. When a custom error is set (via `setCustomValidity`) and the element is disabled, the test expects `validationMessage` to be the custom error. The spec on the other hand implies that it should be an empty string.

Per https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-cva-validationmessage

>If this element is not a *candidate for constraint validation* or if this element satisfies its constraints, then return the empty string.

and

>A submittable element is a *candidate for constraint validation* except when a condition has *barred the element* from constraint validation. (For example, an element is barred from constraint validation if it is an object element.)

and

>Constraint validation: If an element is disabled, it is *barred from constraint validation*.

would result in an empty message, yet the updated test expects the custom error to show.

Either the tests or the spec would need to be updated, as at the moment they're conflicting,

fyi @tkent-google @domenic

### PR DESCRIPTION
**Pull request by TimothyGu**
This commit applies two fixes to the validator:

1. Reapply the conditions for each clone of the element created in `iterate_over`.

   This fixes valueMissing.html's "[select] Selected the option with value equals to 1" test, that was failing on all browsers.

2. Fix the expectation for `validationMessage` when the element is disabled. This fixes #20825.

### CODE REVIEW

**Comment by TimothyGu** [comment]
cc @mfreed7

File: html/semantics/forms/constraints/support/validator.js [hunk 1]
```diff
@@ -398,12 +389,27 @@ var validator = {
   iterate_over: function(ctl, data) {
     // Iterate over normal, disabled, readonly, and both.
     var ctlDisabled = ctl.cloneNode(true);
+    this.set_conditions(ctlDisabled, data.conditions);
     ctlDisabled.disabled = true;
+    if (data.dirty)
+      this.set_dirty(ctlDisabled);
```
Comment (tkent-google) [inline html/semantics/forms/constraints/support/validator.js]: this.set_dirty() should be called before the line of |ctlDisabled.disabled = true;| because set_dirty() relies on focus().

File: html/semantics/forms/constraints/support/validator.js [hunk 2]
```diff
@@ -398,12 +389,27 @@ var validator = {
...
     ctlReadonly.readonly = true;
+    if (data.dirty)
+      this.set_dirty(ctlReadonly);
+
     var ctlBoth = ctl.cloneNode(true);
+    this.set_conditions(ctlBoth, data.conditions);
     ctlBoth.disabled = true;
     ctlBoth.readonly = true;
+    if (data.dirty)
+      this.set_dirty(ctlBoth);
```
Comment (tkent-google) [inline html/semantics/forms/constraints/support/validator.js]: Ditto.

**Review by tkent-google — APPROVED** [review]
Thank you for the fix.

File: html/semantics/forms/constraints/support/validator.js (hunk 1 above)
Comment (TimothyGu) [reply html/semantics/forms/constraints/support/validator.js]: Done. I also moved `set_dirty` to before `ctl.readOnly = true;` as `set_dirty` modifies `ctl.value`.

**Comment by mfreed7** [comment]
Thanks for the fix! Sorry I didn't get to this until you already fixed it.
