### PR TITLE
Fix validity.valueMissing tests

### LINKED ISSUE #21007: Tests for validity.valueMissing property are inconsistent with the spec
According to the [specification](https://html.spec.whatwg.org/multipage/#attr-textarea-required), `textarea` elements do not _suffer from being missing_ when they're immutable:

> Constraint validation: If the element has its required attribute specified, **and the element is mutable**, and the element's value is the empty string, then the element is suffering from being missing.

The same applies for `input` elements in textual mode ([spec](https://html.spec.whatwg.org/multipage/#the-required-attribute)):

> Constraint validation: If the element is required, and its value IDL attribute applies and is in the mode value, **and the element is mutable**, and the element's value is the empty string, then the element is suffering from being missing.

`html/semantics/forms/constraints/form-validation-validity-valueMissing.html` and related tests wrongly expect `validity.valueMissing` to be the same for normal, disabled and readonly elements.

### PR DESCRIPTION
**Pull request by teapotd**
These changes fix expectations for `validity.valueMissing` and `validity.valid` for disabled/readonly elements. This fixes #21007.

### CODE REVIEW

**Comment by domenic** [comment]
@TimothyGu has recently looked at this code

File: html/semantics/forms/constraints/support/validator.js [hunk 1]
```diff
@@ -167,14 +167,14 @@ var validator = {
...
+        const {ctl, expected, condStr} = val;
+        if (expected) {
           assert_true(
               ctl.validity.customError,
               'The validity.customError attribute should be true' + condStr);
           // validationMessage returns the empty string if ctl is barred from
-          // constraint validation, which happens if ctl is disabled.
-          if (ctl.disabled) {
+          // constraint validation, which happens if ctl is disabled or readOnly.
+          if (ctl.disabled || ctl.readOnly) {
```
Comment (tkent-google) [inline html/semantics/forms/constraints/support/validator.js]: Why ctl.readOnly check is necessary?

File: html/semantics/forms/constraints/support/validator.js [hunk 2]
```diff
@@ -389,39 +389,54 @@ var validator = {
...
-      {ctl: ctl, data: data, condStr: '.'},
-      {ctl: ctlDisabled, data: data, condStr: ', when control is disabled.'},
-      {ctl: ctlReadonly, data: data, condStr: ', when control is readonly.'},
-      {
+    var variants = [
+      {ctl: ctlNormal, expected: data.expected, condStr: '.'},
+      {ctl: ctlDisabled, expected: expectedImmutable, condStr: ', when control is disabled.'},
+    ];
+
+    if ('readOnly' in ctl) {
```
Comment (tkent-google) [inline html/semantics/forms/constraints/support/validator.js]: `<input type=checkbox readonly>` supports `readOnly` IDL attribute, but it doesn't make the element immutable.

File: html/semantics/forms/constraints/support/validator.js (hunk 1 above)
Comment (teapotd) [reply html/semantics/forms/constraints/support/validator.js]: [Readonly elements are barred from constraint validation so validationMessage should be empty](https://html.spec.whatwg.org/multipage/input.html#attr-input-readonly). There was a typo in iterate_over - `readonly` instead of `readOnly`:

https://github.com/web-platform-tests/wpt/blob/91bd700f07b3fe67d5c582e4ebe954516cd46875/html/semantics/forms/constraints/support/validator.js#L403

As a result elements weren't really readonly so the bug didn't appear. I fixed it in this PR, sorry I forgot to mention that.

Comment (tkent-google) [reply html/semantics/forms/constraints/support/validator.js]: Ack.  `readOnly` affects `validationMessage` according to the standard.

File: html/semantics/forms/constraints/support/validator.js (hunk 2 above)
Comment (teapotd) [reply html/semantics/forms/constraints/support/validator.js]: Only textarea and inputs in textual mode have different test expectations for `valueMissing` based on mutability - if element is immutable `valueMissing` should be always false. I introduced `expectedImmutable` to make it possible to specify it in tests.

Maybe instead of introducing `expectedImmutable` it would be better to do this check in `validator.js` in `test_valueMissing` like it's done for `validationMessage`? Then there will be no need to modify test files, only `validator.js`.

Comment (tkent-google) [reply html/semantics/forms/constraints/support/validator.js]: > Only textarea and inputs in textual mode have different test expectations for `valueMissing` based on mutability 

Ah, you're right.  I thought `<input type=checkbox disabled required>` was NOT suffering from being missing. But it **is** according to https://html.spec.whatwg.org/C/#checkbox-state-(type=checkbox)

> it would be better to do this check in validator.js

I think the code would be complicated because we need to check input types and test_isValid() is also affected.  The current PR looks reasonable as is.

**Review by tkent-google — APPROVED** [review]

**Comment by TimothyGu** [comment]
Sorry for the late response. I overlooked these issues as the jsdom implementation happened to pass these tests due to some bugs, but I have confirmed that they are indeed correct.

cc @mfreed7 for any needed changes in Chrome
